### ISSUE TITLE
inaccurate version bounds et al.

### ISSUE THREAD

**Issue by hvr** [andrewthad/monus#2]
Hi,

I couldn't help but notice there's a few issues with the monus-0.1.0.0 release:

As can be seen on https://matrix.hackage.haskell.org/#/package/monus GHC 7.10 disagrees with the advertised compatibility of `base >= 4.5 && < 5` due to

```
Configuring library for monus-0.1.0.0..
Preprocessing library for monus-0.1.0.0..
Building library for monus-0.1.0.0..

src/Data/Monoid/Monus/Generic.hs:13:8:
    Could not find module ‘Data.Semigroup’
    It is a member of the hidden package ‘semigroups-0.18.5@Jz3m3INQrHB7OCwMUa1FzM’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.18.5@6vBhP1Zoku6HniDcB4OnAf’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.18.5@4hAHYlO0v3c5lsZhxIRFBb’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
<<ghc: 127399184 bytes, 99 GCs, 4564458/12352696 avg/max bytes residency (6 samples), 26M in use, 0.001 INIT (0.001 elapsed), 0.027 MUT (0.040 elapsed), 0.127 GC (0.128 elapsed) :ghc>>
```

Moreover, `containers` is lacking an upper bound.

Finally, the `description` ("Please see README...") is not a proper description for your package (and Hackage will show a link to the README at the end of the description *if* the README exists; therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

**Comment by chessai** [comment]
Thanks for pointing these out! Also, that link is super useful! I haven't seen it before. I just pushed a commit which resolves these issues.

**Comment by chessai** [comment]
I just uploaded a new version which resolves all of the above issues.
